EXTRN read_number :proc
EXTRN calc_offset :proc
EXTRN print_al :proc
EXTRN clear_screen :proc
EXTRN print_letter :proc
EXTRN set_offst :proc
EXTRN is_pixel_painted :proc

EXTRN mode_choose_message :proc

EXTRN draw_line_message_x :proc
EXTRN draw_line_message_y :proc
EXTRN draw_line_message_l :proc
EXTRN draw_line_message_r :proc
EXTRN draw_line_message_md :proc

EXTRN draw_line_message_x1 :proc
EXTRN draw_line_message_y1 :proc

EXTRN draw_line_message_x2 :proc
EXTRN draw_line_message_y2 :proc